spring.application.name=interview-project
spring.application.name=interview-project
server.port=8080

csv.filename=/Users/briandeluca/TestCodeWorkspace/interview-project/data/internal_transactions.csv
json.filename=/Users/briandeluca/TestCodeWorkspace/interview-project/data/processor_settlement.json